# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

# pods生成framework而不是默认的静态库
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

# 私有库源
source 'ssh://git@gitee.com/loadar/aarepos.git'

target 'CPFChain_UIKitApp' do

    platform :ios, '8.0'

    # 链式调用
    pod 'CPFChain'
end
